name: hello

on:
#  push:
#    branches: [main, master]
#  pull_request:
#    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_VERSION: '22'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Print hello world
        run: echo "Hello World"

      - name: Print working directory contents
        run: ls -la

      - name: Print context
        run: |
          echo "Context:"
          echo "GitHub: ${{ toJSON(github) }}"
          echo "Job: ${{ toJSON(job) }}"
          echo "Runner: ${{ toJSON(runner) }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Run ID: ${{ github.run_id }}"

      - name: Print&Write step summary
        run: |
          echo "SHA: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "Bransh: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY