name: Vulnerable
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Greet
        run: |
          echo "Díky za PR: ${{ github.event.pull_request.title }}"
          echo "Autor: ${{ github.event.pull_request.user.login }}"
      - run: echo "Placeholder for npm install etc"
      - name: Comment
        run: gh pr comment ${{ github.event.number }} --body "Build hotov"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}